import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('project api client exposes Codex agent message endpoint', async () => {
    const clientSource = await readFile(new URL('../src/editor/project-api-client.js', import.meta.url), 'utf8');
    const serverSource = await readFile(new URL('../src/server/project-api.ts', import.meta.url), 'utf8');

    assert.match(clientSource, /async sendCodexAgentMessage\(\{[\s\S]*user,[\s\S]*projectId,[\s\S]*conversationId,[\s\S]*threadId,[\s\S]*prompt,[\s\S]*workflow,[\s\S]*\}\)/);
    assert.match(clientSource, /fetch\('\/api\/codex-agent\/messages'/);
    assert.match(clientSource, /async sendCodexAgentMessageStream\(\{[\s\S]*onEvent,[\s\S]*onTask,[\s\S]*onMessage,[\s\S]*\}\)/);
    assert.match(clientSource, /fetch\('\/api\/codex-agent\/messages\/stream'/);
    assert.match(clientSource, /function parseSseResponse\(response, handlers = \{\}\)/);
    assert.match(clientSource, /async sendCodexAgentStepAction\(\{[\s\S]*sessionId,[\s\S]*stepKey,[\s\S]*action,[\s\S]*selectedIndex,[\s\S]*images,[\s\S]*sourceImages,[\s\S]*\}\)/);
    assert.match(clientSource, /fetch\('\/api\/agent\/step-action'/);
    assert.match(clientSource, /async sendCodexAgentStepActionStream\(\{[\s\S]*onTask,[\s\S]*signal,[\s\S]*\}\)/);
    assert.match(clientSource, /fetch\('\/api\/agent\/step-action\/stream'/);
    assert.match(clientSource, /async prepareCameraTrajectory\(\{[\s\S]*humanText,[\s\S]*segmentCount,[\s\S]*sceneBoundsScale,[\s\S]*\}\)/);
    assert.match(clientSource, /camera-trajectory\/prepare/);
    assert.match(clientSource, /async continueCameraTrajectory\(\{[\s\S]*preparedPath,[\s\S]*\}\)/);
    assert.match(clientSource, /camera-trajectory\/continue/);
    assert.match(clientSource, /async optimizeCameraTrajectory\(\{[\s\S]*preparedPath,[\s\S]*\}\)/);
    assert.match(clientSource, /camera-trajectory\/optimize/);
    assert.match(serverSource, /const CODEX_AGENT_PREFIX = '\/api\/codex-agent';/);
    assert.match(serverSource, /const AGENT_STEP_ACTION_PREFIX = '\/api\/agent\/step-action';/);
    assert.match(serverSource, /url\.pathname === `\$\{CODEX_AGENT_PREFIX\}\/messages`/);
    assert.match(serverSource, /url\.pathname === `\$\{CODEX_AGENT_PREFIX\}\/messages\/stream`/);
    assert.match(serverSource, /sendSseHeaders\(res\)/);
    assert.match(serverSource, /writeSse\(res, 'task', task\)/);
    assert.match(serverSource, /writeSse\(res, 'result', result\)/);
    assert.match(serverSource, /url\.pathname === AGENT_STEP_ACTION_PREFIX/);
    assert.match(serverSource, /url\.pathname === `\$\{CODEX_AGENT_PREFIX\}\/step-actions`/);
    assert.match(serverSource, /await codexAgent\.sendMessage\(\{/);
    assert.match(serverSource, /await codexAgent\.handleStepAction\(codexStepActionInputFromBody\(body, controller\.signal\)\)/);
    assert.match(serverSource, /sourceImages: Array\.isArray\(body\.sourceImages\) \? body\.sourceImages : undefined/);
});

test('project api exposes per-user Codex auth status and save endpoints', async () => {
    const clientSource = await readFile(new URL('../src/editor/project-api-client.js', import.meta.url), 'utf8');
    const serverSource = await readFile(new URL('../src/server/project-api.ts', import.meta.url), 'utf8');

    assert.match(clientSource, /async getCodexAuthStatus\(user\)/);
    assert.match(clientSource, /async saveCodexAuth\(\{ user, apiKey \}\)/);
    assert.match(serverSource, /const CODEX_AUTH_PREFIX = '\/api\/codex-auth';/);
    assert.match(serverSource, /url\.pathname === CODEX_AUTH_PREFIX/);
    assert.match(serverSource, /storage\.getUserCodexAuthStatus\(getQueryString\(url, 'user'\)\)/);
    assert.match(serverSource, /storage\.saveUserCodexAuth\(\{/);
});

test('project api exposes per-user API config endpoints for pipeline API and components 3D providers', async () => {
    const clientSource = await readFile(new URL('../src/editor/project-api-client.js', import.meta.url), 'utf8');
    const serverSource = await readFile(new URL('../src/server/project-api.ts', import.meta.url), 'utf8');
    const storageSource = await readFile(new URL('../src/server/project-storage.ts', import.meta.url), 'utf8');
    const configSource = await readFile(new URL('../src/server/components-3d-config.ts', import.meta.url), 'utf8');
    const statusSource = await readFile(new URL('../src/server/components-3d-status.ts', import.meta.url), 'utf8');

    assert.match(clientSource, /async getUserApiConfig\(user\)/);
    assert.match(clientSource, /async saveUserApiConfig\(\{ user, config \}\)/);
    assert.match(serverSource, /const USER_API_CONFIG_PREFIX = '\/api\/user-api-config';/);
    assert.match(serverSource, /url\.pathname === USER_API_CONFIG_PREFIX/);
    assert.match(serverSource, /async function createUserApiConfigResponse\([\s\S]*config: UserApiConfig,[\s\S]*options: \{ includeTrellisStatus\?: boolean \} = \{\},[\s\S]*\): Promise<ClientUserApiConfigResponse>/);
    assert.match(serverSource, /includeTrellisStatus && config\.components3D\.provider === 'trellis\.2'/);
    assert.match(serverSource, /await createUserApiConfigResponse\(await storage\.getUserApiConfig\(getQueryString\(url, 'user'\)\)\)/);
    assert.match(serverSource, /includeTrellisStatus: Object\.prototype\.hasOwnProperty\.call\(configRecord, 'components3D'\)/);
    assert.match(storageSource, /const USER_API_CONFIG_FILE = 'api_config\.json';/);
    assert.match(storageSource, /async getUserApiConfig\(userInput: string\): Promise<UserApiConfig>/);
    assert.match(storageSource, /async saveUserApiConfig\(input: SaveUserApiConfigInput\): Promise<UserApiConfig>/);
    assert.match(configSource, /pipelineApi: defaultPipelineApiConfig\(\),/);
    assert.match(configSource, /codex: defaultCodexApiConfig\(\),/);
    assert.match(configSource, /function defaultPipelineApiConfig\(\)/);
    assert.match(configSource, /apiBase: DEFAULT_PIPELINE_API_BASE,/);
    assert.match(configSource, /baseUrl: 'https:\/\/ai3d\.tencentcloudapi\.com'/);
    assert.match(configSource, /region: 'ap-guangzhou'/);
    assert.match(configSource, /version: '2025-05-13'/);
    assert.match(configSource, /secretKey: '',/);
    assert.match(configSource, /hasSecretKey: Boolean\(config\.secretKey\)/);
    assert.match(statusSource, /export function buildComponents3DTrellisStatusUrl\(config: Components3DEndpointConfig\): string/);
    assert.match(statusSource, /export function summarizeComponents3DTrellisStatusPayload\(/);
    assert.match(statusSource, /export async function queryComponents3DTrellisStatus\(/);
    assert.match(statusSource, /components3DEndpointBaseUrl\(config\)}\/status/);
    assert.match(storageSource, /await chmod\(this\.getUserApiConfigPath\(userId\), 0o600\);/);
});

test('editor routes server project agent prompts through Codex before falling back to mock responses', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const cssSource = await readFile(new URL('../public/editor.css', import.meta.url), 'utf8');

    assert.match(source, /agentCodexConversationId:\s*'',/);
    assert.match(source, /agentCodexThreadId:\s*'',/);
    const runtimeStatusStart = source.indexOf('function getAgentRuntimeStatus()');
    const runtimeLabelStart = source.indexOf('function renderProjectBrowserCodexAuthStatus()');
    assert.notEqual(runtimeStatusStart, -1);
    assert.notEqual(runtimeLabelStart, -1);
    const runtimeStatusSource = source.slice(runtimeStatusStart, runtimeLabelStart);
    assert.match(runtimeStatusSource, /state\.workspace\?\.mode !== 'server'/);
    assert.match(runtimeStatusSource, /!state\.projectSession\.codexAuthHasAuth/);
    assert.match(runtimeStatusSource, /agentRuntimeReady/);
    assert.match(source, /function canUseServerCodexAgent\(\) \{\s*return getAgentRuntimeStatus\(\)\.ready;\s*\}/);
    assert.match(source, /function startAgentEndpointDebug\(\{[\s\S]*waiting for \$\{endpoint\}[\s\S]*taskEvents: summarizeCodexTaskEvents\(result\)/);
    assert.match(source, /function isAgentDebugEnabled\(workflowId = ''\) \{[\s\S]*workflowId === 'camera-direct'/);
    assert.doesNotMatch(source, /messages\.codexAgentRunning/);
    const runSessionAttemptStart = source.indexOf('function runServerCodexAgentSessionAttempt');
    const startResponseStart = source.indexOf('function startServerCodexAgentResponse');
    assert.notEqual(runSessionAttemptStart, -1);
    assert.notEqual(startResponseStart, -1);
    const handleStepActionStart = source.indexOf('async function handleAgentStepAction');
    assert.notEqual(handleStepActionStart, -1);
    const startResponseSource = source.slice(startResponseStart, handleStepActionStart);
    assert.match(startResponseSource, /const handle = openAgentAssistantMessage\(\{/);
    assert.match(startResponseSource, /workflow: workflowId,/);
    assert.match(startResponseSource, /isLoading: true,/);
    assert.match(startResponseSource, /projectApi\.sendCodexAgentMessageStream\(\{/);
    assert.match(source, /function shouldCreatePendingCodexTaskSession\(workflowId\) \{[\s\S]*shouldUseScenePipelineState\(workflowId\) \|\| workflowId === 'camera-direct'/);
    assert.match(startResponseSource, /if \(shouldCreatePendingCodexTaskSession\(workflowId\)\) \{[\s\S]*createPendingCodexTaskSession/);
    assert.doesNotMatch(startResponseSource, /\$scene-skill\(\?=\\s\|\$\)/);
    assert.doesNotMatch(startResponseSource, /\/\\\$camera-skill\(\?=\\s\|\$\)\/i/);
    assert.doesNotMatch(startResponseSource, /runVisionaryCameraTrajectoryAgentResponse\(\{/);
    assert.match(startResponseSource, /const debug = startAgentEndpointDebug\(\{/);
    assert.match(startResponseSource, /debug\.finish\(result\);/);
    assert.match(startResponseSource, /debug\.finish\(null, error\);/);
    assert.match(startResponseSource, /conversationId: getCodexAgentConversationId\(\),/);
    assert.match(startResponseSource, /threadId: state\.agentCodexThreadId,/);
    assert.match(startResponseSource, /workflow: workflowId,/);
    assert.match(source, /function findAgentWorkflowThreadItemLocation\(itemId\) \{/);
    assert.match(source, /function updateAgentSessionById\(sessionId, updater,[\s\S]*const location = findAgentWorkflowThreadItemLocation\(sessionId\);[\s\S]*location\.items\[location\.index\] = nextSession;[\s\S]*if \(!skipRender && location\.isCurrent\)/);
    assert.match(source, /function updateAgentMessageById\(messageId, updater\) \{[\s\S]*const location = findAgentWorkflowThreadItemLocation\(messageId\);[\s\S]*if \(location\.isCurrent\)/);
    const submitPromptStart = source.indexOf('function submitAgentPrompt');
    assert.notEqual(submitPromptStart, -1);
    const submitPromptSource = source.slice(submitPromptStart);
    assert.match(submitPromptSource, /const workflowId = getAgentWorkflowForPrompt\(effectivePrompt, state\.agentWorkflow\);/);
    assert.doesNotMatch(submitPromptSource, /setAgentWorkflow\(workflowId\);/);
    assert.ok(submitPromptSource.indexOf('if (canUseServerCodexAgent()) {') < submitPromptSource.indexOf('startMockAgentResponse(workflowId, effectivePrompt, attachments);'));
    assert.match(submitPromptSource, /startServerCodexAgentResponse\(workflowId, effectivePrompt, attachments\);/);
    assert.match(submitPromptSource, /return;/);
    assert.match(submitPromptSource, /startMockAgentResponse\(workflowId, effectivePrompt, attachments\);/);
    const runSessionAttemptSource = source.slice(runSessionAttemptStart, startResponseStart);
    assert.match(runSessionAttemptSource, /projectApi\.sendCodexAgentMessageStream\(\{/);
    assert.match(runSessionAttemptSource, /if \(workflowId === 'camera-direct'\) \{[\s\S]*completeCameraDirectResultWithHostRender\(\{/);
    assert.match(runSessionAttemptSource, /const debug = startAgentEndpointDebug\(\{/);
    assert.match(runSessionAttemptSource, /debug\.finish\(result\);/);
    assert.match(runSessionAttemptSource, /debug\.finish\(null, error\);/);
    assert.match(runSessionAttemptSource, /conversationId: getCodexAgentConversationId\(\),/);
    assert.match(runSessionAttemptSource, /threadId: state\.agentCodexThreadId,/);
    assert.match(runSessionAttemptSource, /workflow: workflowId,/);

    const completeAttemptStart = source.indexOf('function completeServerCodexAgentSessionAttempt');
    assert.notEqual(completeAttemptStart, -1);
    const completeAttemptSource = source.slice(completeAttemptStart, runSessionAttemptStart);
    assert.match(completeAttemptSource, /if \(hasCodexTaskSignal\(result\)\)/);
    assert.match(completeAttemptSource, /createCodexTaskAttemptFromResult\(\{/);
    assert.match(completeAttemptSource, /if \(!shouldUseScenePipelineState\(workflowId\)\) return nextSession;/);
    assert.match(completeAttemptSource, /replaceAgentSessionAttempt\(nextSession, attemptId,/);
    assert.match(completeAttemptSource, /deriveScenePipelineState\(nextSession, attempt\)/);

    const sessionActionStart = source.indexOf('async function handleAgentSessionAction');
    assert.notEqual(sessionActionStart, -1);
    assert.notEqual(submitPromptStart, -1);
    const sessionActionSource = source.slice(sessionActionStart, submitPromptStart);
    assert.match(sessionActionSource, /if \(session\.workflow === 'camera-direct'\) \{[\s\S]*createAgentGenerationAttempt\(\{[\s\S]*blocks:\s*\[\],[\s\S]*steps:\s*\[\],[\s\S]*status:\s*'running'[\s\S]*runServerCodexAgentSessionAttempt\(\{/);
    assert.match(sessionActionSource, /if \(session\.workflow === 'camera-direct'\) \{[\s\S]*cancelAgentCameraRenderJob\(\);[\s\S]*resetAgentCameraTrajectoryPreviewForRetry\(\);/);
    assert.match(sessionActionSource, /runServerCodexAgentSessionAttempt\(\{[\s\S]*workflowId: session\.workflow,[\s\S]*prompt: retryPrompt,[\s\S]*sessionId,[\s\S]*attemptId: nextAttempt\.id/);
    assert.doesNotMatch(sessionActionSource, /runVisionaryCameraTrajectoryAgentResponse\(\{/);
    assert.ok(sessionActionSource.indexOf("if (session.workflow === 'camera-direct')") < sessionActionSource.indexOf('const interruptedStepContext = getInterruptedAgentStepContext'));
    assert.match(sessionActionSource, /if \(canUseServerCodexAgent\(\)\) \{/);
    assert.match(sessionActionSource, /runServerCodexAgentSessionAttempt\(\{/);
    assert.match(sessionActionSource, /workflowId: session\.workflow,/);
    assert.match(sessionActionSource, /attemptId: nextAttempt\.id,/);
    assert.ok(sessionActionSource.indexOf('runServerCodexAgentSessionAttempt({') < sessionActionSource.indexOf('createMockAgentAttemptBlocks(session.workflow)'));
});

test('editor renders Codex pending state as a spinner inside the assistant bubble', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const css = await readFile(new URL('../public/editor.css', import.meta.url), 'utf8');

    assert.match(source, /isLoading = false,[\s\S]*\} = \{\}\) \{/);
    assert.match(source, /message\.isLoading = Boolean\(isLoading\);/);
    assert.match(source, /const isLoading = isAssistant && message\.isLoading;/);
    assert.match(source, /const isThinkingBeforeMcp = session\.archiveState === 'active'[\s\S]*attempt\?\.status === 'running'[\s\S]*attemptBlocks\.length <= 0;/);
    assert.match(source, /agent-message-text \$\{isThinkingBeforeMcp \? 'agent-thinking-text' : ''\}/);
    assert.match(source, /agent-message-loading-spinner/);
    assert.match(source, /message\.isLoading = false;/);
    assert.match(
        css,
        /\.agent-message-bubble\s*\{[\s\S]*position:\s*relative;[\s\S]*\}/
    );
    assert.match(
        css,
        /\.agent-message-loading-spinner\s*\{[\s\S]*position:\s*absolute;[\s\S]*top:\s*10px;[\s\S]*right:\s*12px;[\s\S]*animation:\s*spin 0\.8s linear infinite;[\s\S]*\}/
    );
    assert.match(css, /\.agent-thinking-text::after\s*\{[\s\S]*animation:\s*agentThinkingDots 1\.2s steps\(1, end\) infinite;[\s\S]*\}/);
    assert.match(css, /@keyframes agentThinkingDots\s*\{[\s\S]*content:\s*'\.';[\s\S]*content:\s*'\.\.';[\s\S]*content:\s*'\.\.\.';[\s\S]*\}/);
});

test('scene task controls interrupt the whole attempt without exposing task apply', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const renderStart = source.indexOf('function renderAgentSessionItem(session)');
    const renderEnd = source.indexOf('function invalidateAgentMessageScrollbarMetrics', renderStart);
    const sessionActionStart = source.indexOf('async function handleAgentSessionAction');
    const sessionActionEnd = source.indexOf('function submitAgentPrompt', sessionActionStart);
    const renderSource = source.slice(renderStart, renderEnd);
    const actionSource = source.slice(sessionActionStart, sessionActionEnd);

    assert.match(renderSource, /resolveAgentSessionActionAvailability\(\{[\s\S]*workflow: session\.workflow/);
    assert.match(renderSource, /session\.workflow === 'scene-build' \? '' : `<button[^`]*data-agent-session-action="apply"/);
    assert.match(actionSource, /if \(action === 'apply'\) \{[\s\S]*if \(session\.workflow === 'scene-build'\) return;/);
    assert.match(actionSource, /if \(session\.workflow === 'scene-build'\) \{[\s\S]*abortSceneSkillExecutions\(\{[\s\S]*clearAgentSceneInsertPreviewForContext/);
    assert.match(actionSource, /createPendingSceneSkillAttempt\(\{[\s\S]*appendAgentSessionWholeTaskRetryAttempt\(interrupted, nextAttempt\)/);
    assert.match(actionSource, /interruptSceneSkillAttempt\(attempt, 'canceled'\)/);
    assert.match(actionSource, /setAgentSessionArchiveState\(\{ \.\.\.current, attempts \}, \{[\s\S]*archiveState: 'canceled'/);
    assert.match(source, /signal: requestController\?\.signal/);
    assert.match(source, /if \(error\?\.name === 'AbortError'\) return;/);
});

test('editor shows Codex generation controls only after an explicit task signal', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const cssSource = await readFile(new URL('../public/editor.css', import.meta.url), 'utf8');
    const layoutServerSource = await readFile(new URL('../src/server/mcp/new-pipeline-layout-server.ts', import.meta.url), 'utf8');
    const startFunction = source.match(/function startServerCodexAgentResponse\(workflowId, prompt, attachments = \[\]\) \{[\s\S]*?\n\}/)?.[0] || '';
    const createSessionFunction = source.match(/function createCodexTaskSessionFromResult\([\s\S]*?\n\}/)?.[0] || '';

    assert.match(source, /function hasCodexTaskSignal\(result\) \{[\s\S]*result\?\.task\?\.started/);
    assert.match(source, /function createCodexTaskSessionFromResult\([\s\S]*createAgentProgressBlock/);
    assert.match(source, /const SCENE_PIPELINE_STEP_DEFS = \[[\s\S]*key: 'main-image'[\s\S]*key: 'top-view'[\s\S]*key: 'layout'[\s\S]*key: 'object-images'[\s\S]*key: 'components-3d'[\s\S]*key: 'insert-scene'/);
    assert.doesNotMatch(source, /key: 'front-view'/);
    assert.match(source, /function createScenePipelineSteps\(\{/);
    assert.match(source, /function createPendingCodexTaskSession\(\{/);
    assert.match(source, /statusText: t\('common\.generating'\)/);
    assert.match(source, /indeterminate: true/);
    assert.match(source, /function advanceAgentPipelineAfterStepApply\(context\)/);
    assert.match(source, /const progressImages = Array\.isArray\(result\?\.images\)/);
    assert.match(source, /createAgentProgressBlock\(\{[\s\S]*images: progressImages/);
    assert.match(source, /selectedIndex: 0/);
    assert.match(source, /applied: false/);
    assert.match(source, /actions: isFailedTask \? \['cancel', 'retry'\] : \(progressImages\.length > 0 \? \['cancel', 'retry', 'apply'\] : \[\]\)/);
    assert.match(source, /const steps = createScenePipelineSteps\(\{[\s\S]*mainImageBlock: progressBlock/);
    assert.match(source, /steps,/);
    assert.match(source, /const attemptBlocks = getAgentAttemptStepBlocks\(attempt\);[\s\S]*renderAgentBlocks\(attemptBlocks,/);
    assert.match(source, /<details class="agent-block agent-block-progress agent-step-block/);
    assert.match(source, /class="agent-step-gallery/);
    assert.match(source, /data-agent-step-gallery-nav="prev"/);
    assert.match(source, /data-agent-step-gallery-nav="next"/);
    assert.match(source, /data-agent-step-candidate-nav="prev"/);
    assert.match(source, /data-agent-step-candidate-nav="next"/);
    assert.match(source, /images: galleryImages/);
    assert.match(source, /sceneCandidateIndex: gallery\.candidateIndex/);
    assert.match(source, /context: \{ selectedImageIndex: selectedIndex \}/);
    assert.match(source, /\$\{selectedIndex \+ 1\} \/ \$\{images\.length\}/);
    assert.doesNotMatch(source, /agent-step-gallery-dots/);
    assert.match(source, /function getAgentStepImageGlbPath\(image\)/);
    assert.match(source, /metadata\?\.glbPaths/);
    assert.doesNotMatch(source, /if \(metadata\?\.kind === 'components_3d'\) return '';/);
    assert.match(source, /function getAgentStepImageThumbnailSrc\(image\)/);
    assert.match(source, /metadata\?\.thumbnailPath[\s\S]*metadata\?\.frontRenderPath[\s\S]*metadata\?\.previewPath/);
    assert.doesNotMatch(source, /function getAgentStepImageInferredFrontRenderPath\(image\)/);
    assert.ok(source.includes("const inferredProjectId = assetPath.match(/^agent_history\\/assets\\/new_pipeline\\/([^/]+)\\//)?.[1] || '';"));
    assert.match(source, /if \(!projectId\) return '';/);
    assert.match(source, /function createAgentStepImageViewer3DBlock\(block, image, selectedIndex = 0\)/);
    assert.match(source, /assetUrl: getAgentStepImageProjectAssetUrl\(glbPath\)/);
    assert.match(source, /function isCameraPipelineStepKey\(stepKey\) \{[\s\S]*CAMERA_PIPELINE_STAGE_PLAN\.includes\(String\(stepKey \|\| ''\)\);[\s\S]*\}/);
    assert.match(source, /function isAgentStepGalleryNavigationLocked\(block, attempt = null\) \{[\s\S]*attempt\?\.status === 'interrupted'[\s\S]*typeof block\?\.galleryLocked === 'boolean'[\s\S]*isCameraPipelineStepKey\(block\?\.stepKey\)[\s\S]*Boolean\(block\?\.applied\);[\s\S]*\}/);
    assert.match(source, /function renderAgentStepGalleryMain\(\{/);
    assert.match(source, /const isGalleryLocked = isAgentStepGalleryNavigationLocked\(block,[\s\S]*!isGalleryLocked && selectedIndex > 0[\s\S]*!isGalleryLocked && selectedIndex < images\.length - 1/);
    assert.match(source, /data-agent-viewer-block-id="\$\{escapeHtml\(viewerBlock\.id\)\}"/);
    assert.doesNotMatch(source, /class="agent-step-viewer-thumb"/);
    assert.match(source, /renderAgentStepGalleryMain\(\{ block, images, selectedImage, selectedIndex, isApplied, isInterruptedAttempt \}\)/);
    assert.match(source, /function updateAgentStepSelectedIndex\(context, selectedIndex\)/);
    assert.match(source, /context\.session\?\.workflow === 'scene-build'[\s\S]*updateSceneSkillAttemptBranch\([\s\S]*\{ render: false \}\);[\s\S]*updateAgentStepGalleryDom\(nextContext\)/);
    assert.match(source, /void updateAgentStepGalleryDom\(nextContext\)\.then\(\(updated\) => \{[\s\S]*if \(updated\) \{[\s\S]*void syncAgent3DBlocks\(\);/);
    assert.match(source, /function restoreAgentMessageScrollPosition\(scrollTop\) \{[\s\S]*dom\.agentMessageScroll\.scrollTop = Math\.min\(Math\.max\(0, scrollTop\), maxScrollTop\);[\s\S]*requestAnimationFrame\(restore\);/);
    assert.match(source, /async function updateAgentStepGalleryDom\(context\)/);
    assert.match(source, /cachedImage = await preloadAgentImageSource\(thumbnailSrc\);[\s\S]*agentStepGalleryUpdateTokens\.get\(context\.blockId\) !== updateToken/);
    assert.match(source, /currentImage\.src = thumbnailSrc;[\s\S]*galleryMain\.innerHTML = renderAgentStepGalleryMain\(\{/);
    assert.match(source, /restoreAgentMessageScrollPosition\(preservedScrollTop\);/);
    assert.match(source, /button\.disabled = isAgentStepGalleryNavigationLocked\(context\.block, context\.attempt\)/);
    assert.match(source, /if \(!context \|\| isAgentStepGalleryNavigationLocked\(context\.block, context\.attempt\)\) return;/);
    assert.match(source, /void syncAgent3DBlocks\(\);/);
    assert.match(source, /skipRender: true/);
    assert.match(source, /function renderAgentStepBlockElement\(context, \{ autoScroll = 'preserve-or-pin-bottom' \} = \{\}\)/);
    assert.match(source, /function getDeferredAgentStepBlockIds\(blocks = \[\]\)/);
    const patchStepStart = source.indexOf('function patchAgentStepBlock');
    const interruptedStepStart = source.indexOf('function getInterruptedAgentStepContext', patchStepStart);
    assert.notEqual(patchStepStart, -1);
    assert.notEqual(interruptedStepStart, -1);
    const patchStepSource = source.slice(patchStepStart, interruptedStepStart);
    assert.match(patchStepSource, /skipRender: true/);
    assert.match(patchStepSource, /const renderOptions = \{ autoScroll: 'preserve-or-pin-bottom' \};[\s\S]*canSyncAgentProgressBlockDom\(context, nextContext\)[\s\S]*syncAgentProgressBlockDom\(nextContext, renderOptions\)[\s\S]*renderAgentStepBlockElement\(nextContext, renderOptions\)/);
    assert.doesNotMatch(patchStepSource, /renderAgentMessages\(/);
    assert.match(source, /data-agent-step-action="\$\{escapeHtml\(action\)\}"/);
    assert.match(source, /const stepActionButton = event\.target\.closest\('\[data-agent-step-action\]'\)/);
    assert.match(source, /handleAgentStepAction\(context, action\)\.catch/);
    assert.match(source, /function handleAgentStepAction\(context, action, \{ assetId = '' \} = \{\}\)/);
    assert.match(source, /projectApi\.sendCodexAgentStepAction\(stepActionInput\)/);
    assert.match(source, /projectApi\.sendCodexAgentStepActionStream\(\{ \.\.\.stepActionInput, onTask: handleStepActionTask \}\)/);
    assert.match(source, /const handleStepActionTask = \(task\)[\s\S]*assetProgress: mergeAgentAssetProgressSnapshots\(currentContext\.block\.assetProgress, task\.assetProgress\)/);
    assert.match(source, /const incomingImages = normalizeAgentTaskPayloadImages\(task\.images\);[\s\S]*mergeAgentIncrementalImages\(streamedImages, incomingImages, streamedSelectedIndex\)/);
    assert.match(source, /images: streamedImages,[\s\S]*selectedIndex: streamedSelectedIndex/);
    assert.match(source, /candidateContext\.selectedImageIndex = resolveAgentImageSelectionIndex\([\s\S]*streamedSelectedImage/);
    assert.match(source, /actions: isRetryAction[\s\S]*filter\(\(item\) => item === 'cancel'\)/);
    assert.match(source, /function renderAgentAssetProgressPopover\(snapshot\)/);
    assert.match(source, /const retryAvailable = items\.length > 0 && items\.every\([\s\S]*\['done', 'failed', 'tle', 'canceled'\]/);
    assert.match(source, /requestAgentExecutionCancellation\(\{[\s\S]*kind: 'asset'[\s\S]*\}\)\.then\(\(\) => handleAgentStepAction\(context, 'retry-asset', \{ assetId \}\)\)/);
    assert.match(source, /async function requestAgentExecutionCancellation\([\s\S]*await projectApi\.cancelAgentExecution\([\s\S]*if \(!result\?\.accepted \|\| result\.state !== 'canceled'\)/);
    assert.match(source, /if \(action === 'retry' && liveContext\.stepKey === 'components-3d' && previousStepExecutionId\) \{[\s\S]*await requestAgentExecutionCancellation\([\s\S]*abortSceneSkillExecutionsFromStep\(liveContext\)/);
    assert.match(source, /if \(session\.workflow === 'scene-build'\) \{[\s\S]*await requestAgentExecutionCancellation\(\{[\s\S]*kind: 'workflow'[\s\S]*abortSceneSkillExecutions\([\s\S]*runServerCodexAgentSessionAttempt\(/);
    assert.match(source, /function formatAgentAssetProgressTrellisHealth\(snapshot\)[\s\S]*busyWorkerCount[\s\S]*workerCount[\s\S]*queue\?\.queued[\s\S]*queue\?\.running/);
    assert.match(source, /function refreshAgentAssetProgressTrellisHealth\(snapshot\)[\s\S]*Date\.now\(\) - agentAssetProgressTrellisStatusLastRequestedAt < 5000[\s\S]*Date\.now\(\) - checkedAt < 5000[\s\S]*projectApi\.getUserApiConfig\(state\.projectSession\.user\)[\s\S]*components3DTrellisStatus/);
    assert.match(source, /void refreshAgentAssetProgressTrellisHealth\(snapshot\);[\s\S]*syncAgentAssetProgressPopover\(snapshot\)/);
    assert.match(source, /agent-asset-progress-popover-provider[\s\S]*agent-asset-progress-popover-health/);
    assert.match(source, /function handleAgentAssetProgressClick\(event\)/);
    assert.match(source, /data-agent-asset-progress-trigger/);
    assert.match(source, /refreshAgentAssetProgressPopoverAnchor\(\)/);
    assert.match(source, /candidate\.context\?\.assetProgress && typeof candidate\.context\.assetProgress === 'object'/);
    assert.match(cssSource, /\.agent-asset-progress-popover\s*\{[\s\S]*position:\s*fixed;[\s\S]*z-index:/);
    assert.match(cssSource, /\.agent-asset-progress-popover-provider\s*\{[\s\S]*justify-content:\s*space-between/);
    assert.match(cssSource, /\.agent-asset-progress-popover-health\s*\{[\s\S]*text-align:\s*right/);
    assert.match(cssSource, /\.agent-progress-track\.has-asset-progress:focus-visible/);
    assert.match(source, /failed:\s*\{[\s\S]*labelKey: 'agent\.pipelineSteps\.pipelineStatuses\.failed'[\s\S]*className: 'is-failed'/);
    assert.match(source, /failed: '失败'/);
    assert.match(source, /failed: 'Failed'/);
    assert.match(source, /queuing:\s*\{[\s\S]*className: 'is-queuing'/);
    assert.match(source, /TLE:\s*\{[\s\S]*className: 'is-failed'/);
    assert.match(cssSource, /\.agent-step-state\.is-failed/);
    assert.match(source, /normalized === 'failed'/);
    assert.match(source, /const liveContext = getAgentStepBlockContextById\(context\?\.sessionId, context\?\.attemptId, context\?\.blockId\) \|\| context;/);
    assert.match(source, /catch \(error\) \{[\s\S]*const timedOut = Number\(latestContext\?\.block\?\.assetProgress\?\.timedOut\) > 0;[\s\S]*statusId: timedOut \? 'TLE' : 'failed'[\s\S]*actions: \['cancel', 'retry'\]/);
    assert.match(source, /const activeContext = resolveActiveSceneSkillContext\(sceneBranch, liveContext\.stepKey\);/);
    assert.match(source, /sourceImages: serializeSceneSkillContextSourceImages\(activeContext\)/);
    assert.match(source, /attemptId: liveContext\.attemptId,[\s\S]*executionId: executionRef\.executionId,[\s\S]*branchRevision: executionRef\.baseRevision,[\s\S]*parentCandidateIds: executionRef\.parentCandidateIds,[\s\S]*activeContext,/);
    assert.match(source, /isSceneSkillExecutionCurrent\(latestContext\.attempt\.sceneBranch, executionRef, result\)/);
    assert.doesNotMatch(source, /serializeAgentSessionStepSourceImage\(liveContext\.session, liveContext\.attempt, 'front-view'\)/);
    assert.match(source, /await advanceAgentPipelineAfterStepApply\(liveContext\)/);
    assert.match(source, /await handleAgentStepAction\(nextContext, 'retry'\)/);
    assert.match(source, /sourceStepKey: stepKey/);
    assert.match(source, /const isCurrentStepStatus = isStepBlock[\s\S]*\/\^\(当前步骤\|Current step\)\$\/i\.test\(String\(block\.statusText \|\| ''\)\.trim\(\)\);/);
    assert.match(source, /let statusText = block\.statusText;[\s\S]*isInterruptedAttempt[\s\S]*\|\| isCurrentStepStatus[\s\S]*statusText = '';/);
    assert.match(source, /const showProgressTrack = !isStepBlock \|\| \([\s\S]*shouldShowAgentStepProgressTrack\(statusId, block\)[\s\S]*!isApplied[\s\S]*!isCanceledStep[\s\S]*!isInterruptedAttempt[\s\S]*\);/);
    assert.match(source, /const forceCollapsed = isStepBlock && Boolean\(context\.stepBlocksCollapsed\);/);
    assert.match(source, /const isOpen = !isStepBlock \|\| \(!forceCollapsed && Boolean\(block\.expanded \|\| block\.isCurrent \|\| \(!isApplied && \(selectedImage \|\| actions\.length > 0 \|\| showContinue\)\)\)\);/);
    assert.match(source, /\$\{showProgressTrack && stepProgressText \? `<span class="agent-block-meta">\$\{stepProgressText\}<\/span>` : ''\}/);
    assert.match(source, /const stepProgressText = block\.indeterminate \? '' : percentText;/);
    assert.match(source, /function isGenericAgentProgressStatusText\(statusText\)/);
    assert.match(source, /isStepBlock && isGenericAgentProgressStatusText\(statusText\)/);
    assert.match(source, /const attemptText = attemptBlocks\.length > 0 && isGenericAgentProgressStatusText\(attempt\?\.text\)/);
    assert.match(source, /\$\{attemptText \? `<div class="agent-message-text/);
    assert.match(source, /function getAgentStepBlockThumbnail\(block\)/);
    assert.match(source, /class="agent-step-summary-thumb"><img src="\$\{escapeHtml\(stepThumbnail\)\}" alt="" loading="eager" decoding="async"><\/span>/);
    assert.match(source, /function getAgentImageAspectRatio\(image\)/);
    assert.match(source, /if \(metadata\.kind === 'layout_bbox'\) return 1;[\s\S]*return null;/);
    assert.match(source, /renderAgentImageAspectStyle\(selectedImage\)/);
    assert.match(source, /loading="eager" decoding="async"/);
    assert.match(source, /const statusId = normalizeAgentPipelineStatusId\(block\.statusId\);[\s\S]*const stepStateLabel = isStepBlock[\s\S]*getAgentPipelineStatusLabel\(statusId\)[\s\S]*: isApplied[\s\S]*\? t\('agent\.pipelineSteps\.applied'\)[\s\S]*: isCanceledStep[\s\S]*\? t\('common\.canceled'\)[\s\S]*: isInterruptedAttempt[\s\S]*\? t\('common\.interrupted'\)[\s\S]*: '';/);
    assert.doesNotMatch(source, /agent-step-current-tag/);
    assert.match(source, /function getAgentPipelineProgressLabel\(attempt\)/);
    assert.match(source, /t\('common\.progressCount', \{[\s\S]*current: completed,[\s\S]*total: scopedBlocks\.length/);
    assert.match(source, /pipelineProgressLabel \|\| \(attempt\?\.status === 'complete'/);
    assert.match(source, /collapseAllSteps: '收纳全部步骤'/);
    assert.match(source, /expandAllSteps: '展开全部步骤'/);
    assert.match(source, /function createAgentStepExpandToggleIcon\(\)/);
    assert.match(source, /class="agent-session-step-toggle-icon"/);
    assert.match(source, /class="agent-session-step-toggle-shape is-menu"/);
    assert.match(source, /class="agent-session-step-toggle-shape is-arrow"/);
    assert.match(source, /data-agent-session-step-toggle="\$\{session\.id\}"/);
    assert.match(source, /stepBlocksCollapsed: !nextExpanded/);
    assert.match(source, /stepBlocksCollapsed: arePipelineStepsCollapsed/);
    assert.match(source, /const sessionStepToggle = event\.target\.closest\('\[data-agent-session-step-toggle\]'\)/);
    assert.match(source, /function captureAgentMessageLayoutAnimation\(options = null\)/);
    assert.match(source, /function prepareAgentMessageLayoutAnimation\(snapshot\)/);
    assert.match(source, /function restoreAgentMessageLayoutAnchor\(snapshot\)/);
    assert.match(source, /function runAgentMessageLayoutAnimation\(animation\)/);
    assert.match(source, /function syncAgentSessionStepBlocksDom\(sessionId, attemptId, expanded\)/);
    assert.match(source, /details\.classList\.remove\('is-deferred-hidden'\);/);
    assert.match(source, /details\.hidden = false;/);
    assert.match(source, /function syncAgentImageFrameAspectRatios\(root = dom\.agentMessageList\)/);
    assert.match(source, /frame\.style\.setProperty\('--agent-image-aspect-ratio', \(width \/ height\)\.toFixed\(4\)\)/);
    assert.match(source, /function retainAgentThumbnailImageCache\(root = dom\.agentMessageList\)/);
    assert.match(source, /function retainAgentCachedImage\(src\) \{[\s\S]*const cachedImage = new Image\(\);/);
    assert.match(source, /async function preloadAgentImageSource\(src\) \{[\s\S]*if \(!cachedImage\.complete\) \{[\s\S]*cachedImage\.addEventListener\('load', resolve, \{ once: true \}\);[\s\S]*await cachedImage\.decode\?\.\(\)\.catch\(\(\) => \{\}\);/);
    assert.match(source, /renderAgentMessages\(\{ autoScroll, animateLayout \}\)/);
    assert.match(source, /renderAgentSessionStepBlocksExpanded\(sessionId, attemptId, !nextCollapsed\);/);
    assert.doesNotMatch(source, /animateAgentSessionStepBlocks\(sessionId, attemptId, !nextCollapsed\);[\s\S]*window\.setTimeout\(\(\) => \{[\s\S]*setAgentSessionStepBlocksExpanded\(sessionId, attemptId, !nextCollapsed\);/);
    assert.match(source, /if \(context\.stepBlocksCollapsed\) \{[\s\S]*blocks\.map\(\(block\) => renderAgentProgressBlock\(block, context\)\)/);
    assert.match(source, /function renderAgentStepImageMetadata\(image\)/);
    assert.match(source, /metadata\.kind === 'components_3d'/);
    assert.match(source, /metadata\.kind === 'insert_scene'/);
    assert.match(source, /insertSceneAsset/);
    assert.match(source, /metadata\.kind !== 'layout_bbox'/);
    assert.match(source, /const actualDetectionCount = toCount\(metadata\.actualDetectionCount\);/);
    assert.match(source, /const provider = normalizeComponents3DProvider\([\s\S]*metadata\.components3DProvider \|\| state\.projectSession\.components3DConfig\?\.provider/);
    assert.match(source, /provider === 'mocked'[\s\S]*legacyDetectionCount \?\? actualDetectionCount \?\? bboxData\.length[\s\S]*actualDetectionCount \?\? bboxData\.length/);
    assert.match(layoutServerSource, /actualDetectionCount: Number\.isFinite\(Number\(result\.detection_count\)\)[\s\S]*Math\.max\(0, Math\.floor\(Number\(result\.detection_count\)\)\)/);
    const renderMetadataFunction = source.match(/function renderAgentStepImageMetadata\(image\) \{[\s\S]*?\n\}/)?.[0] || '';
    assert.doesNotMatch(renderMetadataFunction, /metadata\.bboxJsonPath \? `<span>\$\{escapeHtml\(metadata\.bboxJsonPath\)\}<\/span>` : ''/);
    assert.doesNotMatch(renderMetadataFunction, /metadata\.glbPaths/);
    assert.doesNotMatch(renderMetadataFunction, /components3dAssets/);
    assert.match(source, /appendSceneSkillCandidate\(setSceneSkillStageExecution\(branch, liveContext\.stepKey, null\), candidate\)/);
    assert.match(source, /createSceneSkillCandidateContext\(\{[\s\S]*patch,[\s\S]*result,[\s\S]*images: nextImages/);
    assert.doesNotMatch(source, /await applyAgentSceneInsertPlan\(patch\.sceneInsertPlan\)/);
    assert.match(source, /function buildAgentStepStatesSnapshot\(\)/);
    assert.match(source, /stepStates: buildAgentStepStatesSnapshot\(\)/);
    assert.match(source, /function buildAgentPipelineStatesSnapshot\(\)/);
    assert.match(source, /pipelineStates: buildAgentPipelineStatesSnapshot\(\)/);
    assert.match(source, /function reconcileAgentProgressBlockTiming\(previousBlock, nextBlock, nowIso = new Date\(\)\.toISOString\(\)\)/);
    assert.match(source, /let startedAt = String\(previous\?\.startedAt \|\| nextBlock\.startedAt \|\| ''\)\.trim\(\);/);
    assert.match(source, /function reconcileAgentProgressBlockList\(previousBlocks = \[\], nextBlocks = \[\]\)/);
    assert.match(source, /context\.stepKey === 'layout'[\s\S]*components3DProvider[\s\S]*updateSceneSkillAttemptBranch\(context\.sessionId, context\.attemptId,[\s\S]*updateSceneSkillActiveCandidate\(branch, context\.stepKey,[\s\S]*metadata:[\s\S]*components3DProvider/);
    assert.match(source, /function formatAgentProgressElapsed\(elapsedMs\)[\s\S]*seconds\.toFixed\(1\)[\s\S]*String\(totalSeconds % 60\)\.padStart\(2, '0'\)/);
    assert.match(source, /class="agent-progress-row"[\s\S]*class="agent-progress-elapsed"[\s\S]*data-agent-progress-elapsed[\s\S]*data-started-at=/);
    assert.match(source, /const terminalElapsedText = isStepBlock[\s\S]*isAgentProgressBlockTerminal\(block\)[\s\S]*block\.completedAt/);
    assert.match(source, /class="agent-step-summary-meta">[\s\S]*agent-step-terminal-elapsed[\s\S]*data-agent-terminal-elapsed[\s\S]*agent-step-state/);
    assert.match(source, /function syncAgentTerminalElapsedVisibility\(root = dom\.agentMessageList\)[\s\S]*elapsed\.hidden = false;[\s\S]*meta\.scrollWidth > meta\.clientWidth[\s\S]*titleRect\.right \+ 8 > metaRect\.left[\s\S]*elapsed\.hidden = overflowsMeta \|\| overlapsTitle;/);
    assert.match(source, /function startAgentProgressElapsedLoop\(\)[\s\S]*window\.setInterval\([\s\S]*syncAgentProgressElapsedLabels\(\)[\s\S]*100/);
    assert.match(source, /startAgentProgressElapsedLoop\(\);/);
    assert.match(cssSource, /\.agent-progress-row\s*\{[\s\S]*display:\s*flex;[\s\S]*gap:\s*8px;/);
    assert.match(cssSource, /\.agent-progress-elapsed\s*\{[\s\S]*width:\s*42px;[\s\S]*flex:\s*0 0 42px;[\s\S]*text-align:\s*right;[\s\S]*white-space:\s*nowrap;/);
    assert.match(cssSource, /\.agent-step-terminal-elapsed\s*\{[\s\S]*width:\s*42px;[\s\S]*flex:\s*0 0 42px;[\s\S]*text-align:\s*right;[\s\S]*white-space:\s*nowrap;/);
    assert.match(cssSource, /\.agent-step-terminal-elapsed\[hidden\]\s*\{[\s\S]*display:\s*none !important;/);
    assert.match(source, /const failedBlocks = getAgentAttemptStepBlocks\(activeAttempt\)\.map[\s\S]*reconcileAgentProgressBlockTiming\(block,[\s\S]*statusId: 'failed'/);
    assert.match(source, /function normalizeRestoredAgentAttemptStatus\(status = 'running'\)/);
    assert.match(source, /return normalized === 'running' \? 'interrupted' : normalized;/);
    assert.match(source, /function isAgentAttemptInternallyRunning\(attempt\)/);
    assert.match(source, /blocks\.some\(\(block\) => block\?\.type === 'progress' && block\.indeterminate\)/);
    assert.match(source, /pipelineState\?\.status === 'running'/);
    assert.match(source, /function shouldMarkInterruptedAgentStepBlock\(block\)/);
    assert.match(source, /statusText: shouldMarkInterrupted \? t\('common\.interrupted'\) : block\.statusText/);
    assert.match(source, /function normalizeInterruptedPipelineState\(pipelineState\)/);
    assert.match(source, /status: pipelineState\.status === 'running' \? 'interrupted' : pipelineState\.status/);
    assert.match(source, /status: step\?\.status === 'running' \? 'interrupted' : step\?\.status/);
    assert.match(source, /function normalizeHydratedAgentItems\(items = \[\]\)/);
    assert.match(source, /item\?\.kind === 'message' && item\.isLoading/);
    assert.match(source, /createInterruptedAgentSessionFromLoadingMessage\(item, lastUserPrompt/);
    assert.match(source, /function interruptRunningAgentConversations\(\)/);
    assert.match(source, /function interruptAgentTasksForPageExit\(\)/);
    assert.match(source, /window\.addEventListener\('pagehide', interruptAgentTasksForPageExit\);/);
    assert.match(source, /window\.addEventListener\('beforeunload', interruptAgentTasksForPageExit\);/);
    assert.match(source, /const isInterruptedAttempt = context\?\.attempt\?\.status === 'interrupted';/);
    assert.match(source, /const actions = isInterruptedAttempt && isStepBlock[\s\S]*\? \[\][\s\S]*: \(Array\.isArray\(block\.actions\) \? block\.actions : \[\]\);/);
    assert.match(source, /const isCanceledStep = isStepBlock && \(statusId === 'canceled' \|\| \/\^已取消\|\^Canceled\/i\.test\(String\(block\.statusText \|\| ''\)\)\);/);
    assert.match(source, /let statusText = block\.statusText;/);
    assert.match(source, /isInterruptedAttempt[\s\S]*\|\| isCurrentStepStatus[\s\S]*\|\| \(isApplied && \/\^已应用\|\^Applied\/i\.test\(String\(block\.statusText \|\| ''\)\)\)/);
    assert.match(source, /const showProgressTrack = !isStepBlock \|\| \([\s\S]*shouldShowAgentStepProgressTrack\(statusId, block\)[\s\S]*!isApplied[\s\S]*!isCanceledStep[\s\S]*!isInterruptedAttempt[\s\S]*\);/);
    assert.match(source, /const showInterruptedStepActions = isInterruptedAttempt && isStepBlock && block\.isCurrent && !isApplied && context\.sessionId;/);
    assert.match(source, /showInterruptedStepActions \? `[\s\S]*data-agent-interrupted-step-action="cancel"[\s\S]*data-agent-interrupted-step-action="retry"/);
    assert.match(source, /function getInterruptedAgentStepContext\(sessionId, attemptId = ''\)/);
    assert.match(source, /function resumeInterruptedAgentStepAttempt\(context\)/);
    assert.match(source, /function handleInterruptedAgentStepAction\(context, action\)/);
    assert.match(source, /if \(liveContext\.session\?\.workflow === 'camera-direct'\) \{[\s\S]*await handleAgentSessionAction\(liveContext\.sessionId, 'retry'\);[\s\S]*return;/);
    assert.ok(source.indexOf("if (liveContext.session?.workflow === 'camera-direct')") < source.indexOf('resumeInterruptedAgentStepAttempt(liveContext);'));
    assert.match(source, /resumeInterruptedAgentStepAttempt\(liveContext\);[\s\S]*await handleAgentStepAction\(retryContext, 'retry'\);/);
    assert.match(source, /const interruptedStepActionButton = event\.target\.closest\('\[data-agent-interrupted-step-action\]'\)/);
    assert.match(source, /handleInterruptedAgentStepAction\(context, action\)\.catch/);
    assert.match(source, /const interruptedStepContext = getInterruptedAgentStepContext\(sessionId, activeAttempt\?\.id \|\| ''\);[\s\S]*await handleInterruptedAgentStepAction\(interruptedStepContext, 'retry'\);[\s\S]*return;/);
    assert.match(source, /context\.attempt\?\.status === 'interrupted' \|\| !shouldShowAgentPipelineContinue\(context\)/);
    assert.match(source, /context\.attempt\?\.status === 'interrupted' \|\| !action/);
    assert.match(source, /function createScenePipelineState\(\{/);
    assert.match(source, /isCurrent: Boolean\(block\.isCurrent\)/);
    assert.match(source, /expanded: Boolean\(block\.expanded\)/);
    assert.match(source, /function applyAgentStepStatesToSnapshot\(snapshot\)/);
    assert.match(source, /function applyAgentPipelineStatesToSnapshot\(snapshot\)/);
    assert.match(source, /applyAgentPipelineStatesToSnapshot\(applyAgentStepStatesToSnapshot\(snapshot\)\)/);
    assert.match(source, /const hydratedSnapshot = applyAgentPipelineStatesToSnapshot\(applyAgentStepStatesToSnapshot\(snapshot\)\);/);
    assert.match(source, /blocks: steps/);
    assert.doesNotMatch(createSessionFunction, /createAgentImageBlock/);
    assert.match(source, /if \(hasCodexTaskSignal\(result\)\) \{[\s\S]*replaceAgentMessageWithSession\(handle\.messageId, createCodexTaskSessionFromResult/);
    assert.doesNotMatch(startFunction, /createAgentProgressBlock/);
    assert.doesNotMatch(startFunction, /createAgentGenerationAttempt/);
    assert.doesNotMatch(startFunction, /createAgentSession/);
});

test('editor applies insert-scene plan only after final user confirmation', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const stepActionStart = source.indexOf("async function handleAgentStepAction(context, action, { assetId = '' } = {})");
    const sessionActionStart = source.indexOf('async function handleAgentSessionAction', stepActionStart);
    const stepActionSource = source.slice(stepActionStart, sessionActionStart);
    const createPreviewStart = source.indexOf('async function createAgentSceneInsertPreview');
    const commitPreviewStart = source.indexOf('function commitAgentSceneInsertPreview', createPreviewStart);
    const applyPlanStart = source.indexOf('async function applyAgentSceneInsertPlan', commitPreviewStart);
    const createPreviewSource = source.slice(createPreviewStart, commitPreviewStart);
    const commitPreviewSource = source.slice(commitPreviewStart, applyPlanStart);

    assert.match(source, /async function applyAgentSceneInsertPlan\(plan\) \{/);
    assert.match(source, /let agentSceneInsertPreview = null;/);
    assert.match(source, /const agentCanonicalAssetBlobCache = new Map\(\);/);
    assert.match(source, /function getCachedCanonicalizedServerProjectAsset\(\.\.\.keys\)/);
    assert.match(source, /function rememberCanonicalizedServerProjectAsset\(asset, \.\.\.keys\)/);
    assert.match(source, /async function canonicalizeServerProjectAssetBlob\(\{ sourcePath, fileName, blob \}\)/);
    assert.match(source, /const cached = getCachedCanonicalizedServerProjectAsset\(sourcePath\);[\s\S]*if \(cached\) return cached;/);
    assert.match(source, /const hashHex = await computeAssetContentHashHex\(content\)/);
    assert.match(source, /const relativePath = buildServerAssetRelativePath\(hashHex, fileName \|\| sourcePath \|\| 'asset\.glb'\)/);
    assert.match(source, /const cachedByHash = getCachedCanonicalizedServerProjectAsset\(relativePath, `sha256:\$\{hashHex\}`\);[\s\S]*return rememberCanonicalizedServerProjectAsset\(cachedByHash, sourcePath\)/);
    assert.match(source, /await projectApi\.writeAsset\(\{[\s\S]*relativePath,[\s\S]*content/);
    assert.match(source, /return rememberCanonicalizedServerProjectAsset\(\{[\s\S]*path: relativePath,[\s\S]*hash: hashHex,[\s\S]*content,[\s\S]*\}, sourcePath\);/);
    assert.match(source, /function clearAgentSceneInsertPreviewForContext\(context = null\)/);
    assert.match(source, /async function loadAgentSceneInsertPlanModels\(plan\)/);
    assert.match(source, /async function createAgentSceneInsertPreview\(context, plan\)/);
    assert.match(source, /function commitAgentSceneInsertPreview\(context\)/);
    assert.match(source, /canonicalAssetReferences: createEmptyCanonicalAssetReferenceSnapshot\(\)/);
    assert.match(source, /canonicalAssetGcPlan: createEmptyCanonicalAssetGcPlan\(\)/);
    assert.match(source, /function collectCanonicalAssetReferences\(\{/);
    assert.match(source, /function buildConservativeCanonicalAssetGcPlan\(\{/);
    assert.match(source, /disabled: true,[\s\S]*reason: 'Conservative canonical asset GC is report-only/);
    assert.match(source, /deletable: new Set\(\)/);
    assert.match(source, /collectCanonicalAssetPathsFromValue\(scene\)\.forEach\(\(pathValue\) => addCanonicalAssetReference\(snapshot, 'scene', pathValue\)\)/);
    assert.match(source, /collectCanonicalAssetPathsFromValue\(agentHistory\)\.forEach\(\(pathValue\) => addCanonicalAssetReference\(snapshot, 'agent', pathValue\)\)/);
    assert.match(source, /collectCanonicalAssetPathsFromValue\(preview\)\.forEach\(\(pathValue\) => addCanonicalAssetReference\(snapshot, 'preview', pathValue\)\)/);
    assert.match(source, /paths\.forEach\(\(pathValue\) => addCanonicalAssetReference\(snapshot, 'active', pathValue\)\)/);
    assert.match(source, /refreshCanonicalAssetReferenceState\(\);[\s\S]*if \(state\.selectedModelId === id\)/);
    assert.match(source, /agentSceneInsertPreview = null;[\s\S]*refreshCanonicalAssetReferenceState\(\);[\s\S]*if \(removed > 0\)/);
    assert.match(createPreviewSource, /agentSceneInsertPreview = \{[\s\S]*assetReferences: result\.assetReferences,[\s\S]*\};[\s\S]*refreshCanonicalAssetReferenceState\(\);/);
    assert.match(commitPreviewSource, /agentSceneInsertPreview = null;[\s\S]*refreshCanonicalAssetReferenceState\(\);[\s\S]*markWorkspaceDirty\('agent-insert-scene'\)/);
    assert.match(source, /if \(isServerAgentAssetPath\(relativePath\) \|\| isServerMaterializedAssetPath\(relativePath\)\) \{/);
    assert.match(stepActionSource, /if \(action === 'apply' && liveContext\.stepKey === 'insert-scene'\)/);
    assert.match(stepActionSource, /const plan = activeCandidate\?\.context\?\.sceneInsertPlan \|\| liveContext\.block\?\.sceneInsertPlan/);
    assert.match(stepActionSource, /commitAgentSceneInsertPreview\(\{[\s\S]*candidateId: activeCandidate\?\.id \|\| '',[\s\S]*branchRevision: sceneBranch\.revision/);
    assert.match(stepActionSource, /clearAgentSceneInsertPreviewForContext\(liveContext\)/);
    assert.match(stepActionSource, /createAgentSceneInsertPreview\(\{[\s\S]*candidateId: currentCandidate\?\.id \|\| '',[\s\S]*branchRevision:/);
    assert.match(stepActionSource, /statusText: t\('agent\.pipelineSteps\.insertScenePreviewReady', \{ count: preview\.loaded \}\)/);
    assert.match(stepActionSource, /setAgentSessionArchiveState\(current, \{[\s\S]*archiveState: 'applied'[\s\S]*summaryLabel: t\('common\.applied'\)/);
    assert.match(source, /insertScenePreviewReady: '已在画布生成 \{count\} 个场景对象预览，请检查后应用、重试或取消'/);
    assert.match(source, /insertScenePreviewReady: 'Previewed \{count\} scene objects on the canvas\. Review, then apply, retry, or cancel\.'/);
    assert.match(source, /candidateId: context\?\.candidateId \|\| '',[\s\S]*branchRevision: Number\(context\?\.branchRevision\) \|\| 0/);
    assert.match(source, /projectApi\.getAssetUrl\(\s*state\.projectSession\.user,[\s\S]*state\.projectSession\.activeProjectId,[\s\S]*sourcePath/);
    assert.match(source, /const canonicalAsset = await canonicalizeServerProjectAssetBlob\(\{[\s\S]*sourcePath,[\s\S]*fileName: targetName,[\s\S]*blob/);
    assert.match(source, /assetId: `sha256:\$\{canonicalAsset\.hash\}`/);
    assert.match(source, /path: canonicalAsset\.path/);
    assert.match(source, /const fileForLoad = new File\(\[canonicalAsset\.content\], targetName/);
    assert.match(source, /const useEmbeddedTransformPlacement = transform\.scaleMode === 'embedded';/);
    assert.match(source, /await app\.loadModel\(fileForLoad, \{[\s\S]*sourcePath: canonicalAsset\.path,[\s\S]*suppressLoadingOverlay: true/);
    assert.match(source, /normalizeEmbeddedTransform: useEmbeddedTransformPlacement/);
    assert.match(source, /app\.renameModel\?\.\(loadedModel\.id, targetName, \{[\s\S]*sourcePath: canonicalAsset\.path/);
    assert.match(source, /const embeddedPosition = useEmbeddedTransformPlacement[\s\S]*loadedModel\.position\?\.x[\s\S]*loadedModel\.position\?\.y[\s\S]*loadedModel\.position\?\.z/);
    assert.match(source, /const finalPosition = \[[\s\S]*position\[0\] \+ embeddedPosition\[0\],[\s\S]*position\[1\] \+ embeddedPosition\[1\],[\s\S]*position\[2\] \+ embeddedPosition\[2\],[\s\S]*\];/);
    assert.match(source, /app\.setModelPosition\(loadedModel\.id, finalPosition\[0\], finalPosition\[1\], finalPosition\[2\]\)/);
    assert.match(source, /app\.setModelRotation\(loadedModel\.id, rotation\[0\], rotation\[1\], rotation\[2\]\)/);
    assert.match(source, /app\.setModelScale\(loadedModel\.id, resolveAgentSceneInsertScale\(loadedModel, transform\)\)/);
    assert.match(source, /if \(transform\.scaleMode === 'embedded'\) return 1;/);
    assert.match(source, /function computeObject3DDimensions\(root\)/);
    assert.doesNotMatch(createPreviewSource, /markWorkspaceDirty\('agent-insert-scene'\)/);
    assert.match(commitPreviewSource, /markWorkspaceDirty\('agent-insert-scene'\)/);
    assert.match(source, /session\.workflow === 'scene-build'[\s\S]*clearAgentSceneInsertPreviewForContext\(\{[\s\S]*sessionId,[\s\S]*attemptId: activeAttempt\?\.id \|\| ''/);
});

test('editor scene step retry appends a candidate and projects a dependency-consistent branch', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const stepActionStart = source.indexOf("async function handleAgentStepAction(context, action, { assetId = '' } = {})");
    const advanceStart = source.indexOf('async function advanceAgentPipelineAfterStepApply', stepActionStart);
    assert.notEqual(stepActionStart, -1);
    assert.notEqual(advanceStart, -1);
    const stepActionSource = source.slice(stepActionStart, advanceStart);

    assert.match(source, /function projectSceneSkillBranchToBlocks\(attempt, sceneBranch = attempt\?\.sceneBranch\)/);
    assert.match(source, /const gallery = getSceneSkillCandidateGallery\(branch, block\.stepKey\)/);
    assert.match(source, /images: galleryImages,[\s\S]*sceneCandidateIds: gallery\.candidateIds/);
    assert.match(source, /if \(!candidate\) \{[\s\S]*statusId: 'pending',[\s\S]*images: \[\],[\s\S]*sceneInsertPlan: undefined/);
    assert.match(stepActionSource, /if \(action === 'retry'\) \{[\s\S]*abortSceneSkillExecutionsFromStep\(liveContext\);/);
    assert.match(stepActionSource, /createSceneSkillCandidate\(\{[\s\S]*parentCandidateIds: executionRef\.parentCandidateIds/);
    assert.match(stepActionSource, /appendSceneSkillCandidate\(setSceneSkillStageExecution\(branch, liveContext\.stepKey, null\), candidate\)/);
    assert.doesNotMatch(stepActionSource, /resetDownstreamScenePipelineStepsForRetry\(liveContext\)/);
});

test('editor preserves failed initial scene-build task state with retry and cancel actions', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const attemptStart = source.indexOf('function createCodexTaskAttemptFromResult');
    const sessionStart = source.indexOf('function createCodexTaskSessionFromResult', attemptStart);
    assert.notEqual(attemptStart, -1);
    assert.notEqual(sessionStart, -1);
    const attemptSource = source.slice(attemptStart, sessionStart);

    assert.match(attemptSource, /const taskStatusId = normalizeAgentPipelineStatusId\(task\.statusId\);/);
    assert.match(attemptSource, /const isFailedTask = taskStatusId === 'failed' \|\| taskStatusId === 'TLE';/);
    assert.match(attemptSource, /statusId: taskStatusId \|\| \(progressImages\.length > 0 \? 'done' : ''\)/);
    assert.match(attemptSource, /actions: isFailedTask \? \['cancel', 'retry'\] : \(progressImages\.length > 0 \? \['cancel', 'retry', 'apply'\] : \[\]\)/);
    assert.match(attemptSource, /isCurrent: progressImages\.length > 0 \|\| isFailedTask/);
});

test('editor streams task images into the active agent progress step', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const css = await readFile(new URL('../public/editor.css', import.meta.url), 'utf8');
    const runtimeSource = await readFile(new URL('../src/server/codex-agent-runtime.ts', import.meta.url), 'utf8');

    assert.match(source, /const taskImages = Array\.isArray\(task\.images\) \? task\.images : \[\];/);
    assert.match(source, /images: taskImages\.length > 0 \? taskImages : \(Array\.isArray\(block\.images\) \? block\.images : \[\]\)/);
    assert.match(source, /selectedIndex: taskImages\.length > 0 \? taskImages\.length - 1 : block\.selectedIndex/);
    assert.match(source, /function renderAgentBlockArtifacts\(artifacts = \[\]\)/);
    assert.match(css, /\.agent-step-artifacts\s*\{[\s\S]*display:\s*grid;[\s\S]*\}/);
    assert.match(css, /\.agent-step-artifact-text\s*\{[\s\S]*white-space:\s*pre-wrap;[\s\S]*overflow-wrap:\s*anywhere;[\s\S]*\}/);
    assert.match(runtimeSource, /initialViewImages\?: CodexGeneratedImage\[\];/);
    assert.match(runtimeSource, /task\.initialViewImages = initialViewImages;/);
    assert.match(runtimeSource, /task\.directorIntentText = payload\.directorIntentText\.trim\(\);/);
});

test('agent progress text updates preserve live selections with stable keyed DOM', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');
    const popoverRefreshStart = source.indexOf('function refreshAgentAssetProgressPopoverAnchor()');
    const pointerOverStart = source.indexOf('function handleAgentAssetProgressPointerOver', popoverRefreshStart);
    assert.notEqual(popoverRefreshStart, -1);
    assert.notEqual(pointerOverStart, -1);
    const popoverRefreshSource = source.slice(popoverRefreshStart, pointerOverStart);

    assert.match(source, /function doesSelectionIntersectNode\(node\)[\s\S]*selection\.isCollapsed[\s\S]*range\.intersectsNode\(node\)/);
    assert.match(source, /function setSelectionSafeElementText\(element, value\)[\s\S]*currentValue === nextValue[\s\S]*doesSelectionIntersectNode\(element\)[\s\S]*selectionSafeTextPendingValues\.set\(element, nextValue\)[\s\S]*textNode\.data = nextValue/);
    assert.match(source, /function syncAgentProgressElapsedLabels\(root = dom\.agentMessageList\)[\s\S]*setSelectionSafeElementText\(element, formatAgentProgressElapsed/);
    assert.doesNotMatch(source, /element\.textContent = formatAgentProgressElapsed/);
    assert.match(source, /setSelectionSafeElementText\(status, getAgentSessionStatusLabel\(session, attempt\)\)/);
    assert.match(source, /setSelectionSafeElementText\(dom\.progressText, `\$\{Math\.round\(progress\)\}%`\)/);
    assert.match(source, /setSelectionSafeElementText\(dom\.exportProgressText, displayPercent > 0/);
    assert.match(source, /setSelectionSafeElementText\(dom\.timeValue, `\$\{state\.currentTime\.toFixed\(3\)\}s`\)/);

    assert.match(source, /function renderAgentAssetProgressPopover\(snapshot\)[\s\S]*data-agent-asset-progress-summary[\s\S]*data-agent-asset-progress-items/);
    assert.match(source, /function createAgentAssetProgressItemElement\(assetId\)[\s\S]*row\.dataset\.agentAssetProgressId = assetId/);
    assert.match(source, /function syncAgentAssetProgressPopover\(snapshot\)[\s\S]*doesSelectionIntersectNode\(popover\)[\s\S]*agentAssetProgressPendingSnapshot = snapshot[\s\S]*rowsById[\s\S]*list\.insertBefore\(row, expectedRow\)[\s\S]*rowsById\.forEach\(\(row\) => row\.remove\(\)\)/);
    assert.doesNotMatch(source, /popover\.innerHTML = renderAgentAssetProgressPopover\(snapshot\)/);
    assert.match(popoverRefreshSource, /syncAgentAssetProgressPopover\(context\.block\.assetProgress\)[\s\S]*positionAgentAssetProgressPopover\(anchor\)/);
    assert.doesNotMatch(popoverRefreshSource, /innerHTML/);
    assert.match(source, /dom\.agentMessageScroll\?\.addEventListener\('scroll',[\s\S]*positionAgentAssetProgressPopoverAnchor\(\)/);

    assert.match(source, /function canSyncAgentProgressBlockDom\(previousContext, nextContext\)[\s\S]*haveSameAgentProgressBlockStaticFields[\s\S]*showProgressTrack/);
    assert.match(source, /function syncAgentProgressBlockDom\(context,[\s\S]*setSelectionSafeElementText[\s\S]*fill\.style\.width[\s\S]*refreshAgentAssetProgressPopoverAnchor\(\)/);
    assert.match(source, /function renderAgentStepBlockElement\(context,[\s\S]*doesSelectionIntersectNode\(currentElement\)[\s\S]*agentPendingStepRenders\.set/);
    assert.match(source, /function renderAgentSessionElement\(sessionId,[\s\S]*doesSelectionIntersectNode\(currentElement\)[\s\S]*agentPendingSessionRenders\.set/);
    assert.match(source, /function renderAgentMessages\([\s\S]*doesSelectionIntersectNode\(dom\.agentMessageList\)[\s\S]*agentPendingMessageListRender = \{ autoScroll \}/);
    assert.match(source, /function handleAgentProgressSelectionChange\(\)[\s\S]*refreshAgentAssetProgressPopoverAnchor\(\)[\s\S]*flushAgentPendingMessageListRender\(\)[\s\S]*flushAgentPendingSessionRenders\(\)[\s\S]*flushAgentPendingStepRenders\(\)[\s\S]*flushSelectionSafeTextUpdates\(\)/);
    assert.match(source, /document\.addEventListener\('selectionchange', handleAgentProgressSelectionChange\)/);
});

test('insert-scene MCP produces a scene insert plan instead of Blender output', async () => {
    const serverSource = await readFile(new URL('../src/server/mcp/new-pipeline-insert-scene-server.ts', import.meta.url), 'utf8');
    const runtimeSource = await readFile(new URL('../src/server/codex-agent-runtime.ts', import.meta.url), 'utf8');

    assert.match(serverSource, /sceneInsertPlan/);
    assert.match(serverSource, /visionary\.scene_insert_plan/);
    assert.match(serverSource, /bboxJsonPath\(batchDir, imageIndex\)/);
    assert.match(serverSource, /frontOrientationPath/);
    assert.match(serverSource, /matchGlbToLayoutObjects/);
    assert.match(serverSource, /images: \[\]/);
    assert.doesNotMatch(serverSource, /blender_frontpoint_layout\.py/);
    assert.doesNotMatch(serverSource, /layout\.blend/);
    assert.doesNotMatch(serverSource, /blendAsset/);
    assert.doesNotMatch(serverSource, /application\/x-blender/);
    assert.match(runtimeSource, /sceneInsertPlan\?: Record<string, unknown>/);
    assert.match(runtimeSource, /const sceneInsertPlan = readRecord\(result\.sceneInsertPlan\)/);
    assert.match(runtimeSource, /\.\.\.\(hasSceneInsertPlan \? \{ sceneInsertPlan \} : \{\}\)/);
});

test('editor clears Codex thread binding when the active server project changes', async () => {
    const source = await readFile(new URL('../public/editor.js', import.meta.url), 'utf8');

    assert.match(source, /function resetAgentCodexSessionBinding\(\) \{[\s\S]*state\.agentCodexConversationId = '';[\s\S]*state\.agentCodexThreadId = '';[\s\S]*\}/);
    assert.match(source, /state\.projectSession\.activeProjectId = project\?\.id \|\| projectId;\s*state\.projectSession\.activeProjectName = project\?\.name \|\| projectId;\s*resetAgentCodexSessionBinding\(\);/);
    assert.match(source, /state\.projectSession\.activeProjectId = project\?\.id \|\| '';\s*state\.projectSession\.activeProjectName = project\?\.name \|\| projectName;\s*resetAgentCodexSessionBinding\(\);/);
    assert.match(source, /function clearActiveServerProjectSelection\(\) \{[\s\S]*resetAgentCodexSessionBinding\(\);[\s\S]*\}/);
    assert.match(source, /function logoutProjectSession\(\) \{[\s\S]*resetAgentCodexSessionBinding\(\);/);
});
